
services:
  microservice.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq 
      - BusOption:Port=5672  
      - IdentityOption:Adress=http://keycloak:8080/realms/ExampleMikroservice
      - IdentityOption:Issuer=http://keycloak:8080/realms/ExampleMikroservice
      - ConnectionStrings:Redis=redis.db.basket:6379, password= Password12
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
    depends_on:
      - redis.db.basket
      - rabbitmq  
    restart: always
    #   - "8081"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    #   - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  microservice.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq 
      - BusOption:Port=5672  
      - IdentityOption:Adress=http://keycloak:8080/realms/ExampleMikroservice
      - IdentityOption:Issuer=http://keycloak:8080/realms/ExampleMikroservice
      - MongoOption:ConnectionString=mongodb://myuser:Password12@mongo.db.catalog:27017
    ports:
      - "8080"
    depends_on:
      - mongo.db.catalog
      - rabbitmq
    restart: always
  mikroservice.discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq 
      - BusOption:Port=5672  
      - IdentityOption:Adress=http://keycloak:8080/realms/ExampleMikroservice
      - IdentityOption:Issuer=http://keycloak:8080/realms/ExampleMikroservice
      - MongoOption:ConnectionString=mongodb://myuser:Password12@mongo.db.discount:27017
    ports:
      - "8080"
    depends_on:
      - mongo.db.discount
      - rabbitmq
    restart: always
  microservice.file.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq 
      - BusOption:Port=5672  
      - IdentityOption:Adress=http://keycloak:8080/realms/ExampleMikroservice
      - IdentityOption:Issuer=http://keycloak:8080/realms/ExampleMikroservice
    ports:
      - "8080"
    depends_on:
      - rabbitmq
    restart: always

  microservice.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - IdentityOption:Adress=http://keycloak:8080/realms/ExampleMikroservice
      - IdentityOption:Issuer=http://keycloak:8080/realms/ExampleMikroservice
    ports:
      - "8080"
    restart: always

  mikroservice.order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq 
      - BusOption:Port=5672  
      - IdentityOption:Adress=http://keycloak:8080/realms/ExampleMikroservice
      - IdentityOption:Issuer=http://keycloak:8080/realms/ExampleMikroservice
      - AddressUrlOption:PaymentUrl=http://microservice.payment.api:8080/api/v1/Payment
      - ConnectionStrings:SqlServer=Server=sqlserver.db.order,1433;Database=MikroserviceOrderDb;User Id=sa;Password=Sbtu2023**;Trusted_Connection=False;TrustServerCertificate=True;Integrated Security=False
    ports:
      - "8080"
    depends_on:
      - sqlserver.db.order
      - rabbitmq
    restart: always
  microservice.payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq 
      - BusOption:Port=5672  
      - IdentityOption:Adress=http://keycloak:8080/realms/ExampleMikroservice
      - IdentityOption:Issuer=http://keycloak:8080/realms/ExampleMikroservice
    ports:
      - "8080"
    depends_on:
      - rabbitmq
    restart: always

  mikroservice.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - MicroserviceOption:Catalog:BaseUrl=http://microservice.catalog.api:8080
      - MicroserviceOption:File:BaseUrl=http://microservice.file.api:8080
      - MicroserviceOption:Basket:BaseUrl=http://microservice.basket.api:8080
      - MicroserviceOption:Discount:BaseUrl=http://mikroservice.discount.api:8080
      - MicroserviceOption:Order:BaseUrl=http://mikroservice.order.api:8080
      - IdentityOption:Adress=http://keycloak:8080/realms/ExampleMikroservice
      - IdentityOption:BaseAddress=http://keycloak:8080
      - GatewayOption:BaseAddress=http://microservice.gateway:8080
    ports:
      - "5050:8080"
    restart: always
