@baseAddress = http://localhost:5131
###
POST {{baseAddress}}/api/v1/orders
Content-Type: application/json
Accept: application/json
{
 "DiscountRate": 0.1,
 "Address": {
   "Province": "Istanbul",
   "District": "Kadikoy",
   "Street": "Rasimpaþa",
   "ZipCode": "34716",
   "Line": "Rasimpaþa Mah. No:16"
 },
 "Payment": {
   "CardName": "John Doe",
   "CardNumber": "1234-5678-9012-3456",
   "Expiration": "12/25",
   "CVV": "123"
 },
 "Items": [
   {
     "ProductId": 1,
     "ProductName": "Product 1",
     "UnitPrice": 100
   },
   {
     "ProductId": 2,
     "ProductName": "Product 2",
     "UnitPrice": 50
   }
 ]"
}
###
